### ISSUE TITLE
Request for requirements.txt file

### ISSUE THREAD

**Issue by pittacus** [nitzanlab/biolord_reproducibility#1]
I kindly request that you consider adding a `requirements.txt` file to the repository. This would greatly benefit users who want to quickly set up the required dependencies to work with your project. However, not pinning the package versions in the `requirements.txt` file can sometimes lead to issues, as using default or non-pinned versions may cause compatibility problems and unexpected behavior during installation.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 model.train(
      2     max_epochs=200,
      3     batch_size=512,
      4     plan_kwargs=trainer_params,
      5     early_stopping=True,
      6     early_stopping_patience=20,
      7     check_val_every_n_epoch=10,
      8     num_workers=0,
      9 )

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/biolord/_model.py:707, in Biolord.train(self, max_epochs, use_gpu, train_size, validation_size, plan_kwargs, batch_size, early_stopping, **trainer_kwargs)
    699 root_dir = (
    700     os.path.join(root_dir, f"{self.__class__.__name__}/")
    701     if self.model_name is None
    702     else os.path.join(root_dir, f"{self.model_name}_{self.__class__.__name__}/")
    703 )
    705 trainer_kwargs["default_root_dir"] = trainer_kwargs.pop("default_root_dir", root_dir)
--> 707 runner = TrainRunner(
    708     self,
    709     training_plan=self.training_plan,
    710     data_splitter=self.data_splitter,
    711     max_epochs=max_epochs,
    712     use_gpu=use_gpu,
    713     early_stopping_monitor=monitor,
    714     early_stopping_mode="max",
    715     enable_checkpointing=enable_checkpointing,
    716     **trainer_kwargs,
    717 )
    719 return runner()

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/scvi/train/_trainrunner.py:85, in TrainRunner.__init__(self, model, training_plan, data_splitter, max_epochs, use_gpu, accelerator, devices, **trainer_kwargs)
     83 self.lightning_devices = lightning_devices
     84 self.device = device
---> 85 self.trainer = self._trainer_cls(
     86     max_epochs=max_epochs,
     87     accelerator=accelerator,
     88     devices=lightning_devices,
     89     **trainer_kwargs,
     90 )

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/scvi/train/_trainer.py:139, in Trainer.__init__(self, accelerator, devices, benchmark, check_val_every_n_epoch, max_epochs, default_root_dir, enable_checkpointing, num_sanity_val_steps, enable_model_summary, early_stopping, early_stopping_monitor, early_stopping_min_delta, early_stopping_patience, early_stopping_mode, enable_progress_bar, progress_bar_refresh_rate, simple_progress_bar, logger, log_every_n_steps, **kwargs)
    136 if logger is None:
    137     logger = SimpleLogger()
--> 139 super().__init__(
    140     accelerator=accelerator,
    141     devices=devices,
    142     benchmark=benchmark,
    143     check_val_every_n_epoch=check_val_every_n_epoch,
    144     max_epochs=max_epochs,
    145     default_root_dir=default_root_dir,
    146     enable_checkpointing=enable_checkpointing,
    147     num_sanity_val_steps=num_sanity_val_steps,
    148     enable_model_summary=enable_model_summary,
    149     logger=logger,
    150     log_every_n_steps=log_every_n_steps,
    151     enable_progress_bar=enable_progress_bar,
    152     **kwargs,
    153 )

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/lightning/pytorch/utilities/argparse.py:70, in _defaults_from_env_vars.<locals>.insert_env_defaults(self, *args, **kwargs)
     67 kwargs = dict(list(env_variables.items()) + list(kwargs.items()))
     69 # all args were already moved to kwargs
---> 70 return fn(self, **kwargs)

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py:427, in Trainer.__init__(self, accelerator, strategy, devices, num_nodes, precision, logger, callbacks, fast_dev_run, max_epochs, min_epochs, max_steps, min_steps, max_time, limit_train_batches, limit_val_batches, limit_test_batches, limit_predict_batches, overfit_batches, val_check_interval, check_val_every_n_epoch, num_sanity_val_steps, log_every_n_steps, enable_checkpointing, enable_progress_bar, enable_model_summary, accumulate_grad_batches, gradient_clip_val, gradient_clip_algorithm, deterministic, benchmark, inference_mode, use_distributed_sampler, profiler, detect_anomaly, barebones, plugins, sync_batchnorm, reload_dataloaders_every_n_epochs, default_root_dir)
    423 self.accumulate_grad_batches = accumulate_grad_batches
    425 # init callbacks
    426 # Declare attributes to be set in _callback_connector on_trainer_init
--> 427 self._callback_connector.on_trainer_init(
    428     callbacks,
    429     enable_checkpointing,
    430     enable_progress_bar,
    431     default_root_dir,
    432     enable_model_summary,
    433     max_time,
    434 )
    436 # init data flags
    437 self.check_val_every_n_epoch: Optional[int]

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/callback_connector.py:79, in _CallbackConnector.on_trainer_init(self, callbacks, enable_checkpointing, enable_progress_bar, default_root_dir, enable_model_summary, max_time)
     76 self._configure_model_summary_callback(enable_model_summary)
     78 self.trainer.callbacks.extend(_load_external_callbacks("lightning.pytorch.callbacks_factory"))
---> 79 _validate_callbacks_list(self.trainer.callbacks)
     81 # push all model checkpoint callbacks to the end
     82 # it is important that these are the last callbacks to run
     83 self.trainer.callbacks = self._reorder_callbacks(self.trainer.callbacks)

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/callback_connector.py:219, in _validate_callbacks_list(callbacks)
    218 def _validate_callbacks_list(callbacks: List[Callback]) -> None:
--> 219     stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
    220     seen_callbacks = set()
    221     for callback in stateful_callbacks:

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/callback_connector.py:219, in <listcomp>(.0)
    218 def _validate_callbacks_list(callbacks: List[Callback]) -> None:
--> 219     stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
    220     seen_callbacks = set()
    221     for callback in stateful_callbacks:

File ~/miniconda3/envs/lifei/lib/python3.11/site-packages/lightning/pytorch/utilities/model_helpers.py:34, in is_overridden(method_name, instance, parent)
     32         parent = pl.Callback
     33     if parent is None:
---> 34         raise ValueError("Expected a parent")
     36 from lightning_utilities.core.overrides import is_overridden as _is_overridden
     38 return _is_overridden(method_name, instance, parent)

ValueError: Expected a parent

**Comment by zoepiran** [comment]
Please excuse the late response, we have now added the file :)
